config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboards#show'
  resources :dashboards, only: :show

  resources :companies do
    resources :jobs do
      resources :comments, only: [:show]
    end
  end

  resources :companies, only: [] do
    resources :contacts, only: [:new, :create]
  end

  resources :contacts, only: [:new, :create]

  resources :jobs, only: [:show] do
    resources :comments
  end

  resources :categories

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true, uniqueness: true

  has_many :jobs
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, :created_at, presence: true


  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
end

app/models/company.rb
class Company < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  
  has_many :jobs, dependent: :destroy
  has_many :contacts
end

app/models/contact.rb
class Contact < ApplicationRecord
  # validates :name, :position, presence: true

  belongs_to :company

  # belongs_to :job_contacts, polymorphic: true
  # has_many :contacts, as: :job_contacts
end

app/models/job.rb
class Job < ApplicationRecord
  validates :title, :level_of_interest, :city, :category_id, presence: true

  has_many :comments, as: :commentable

  # has_many :contacts, as: :job_contacts

  belongs_to :category
  belongs_to :company
end

app/models/job_category.rb
class JobCategory < ApplicationRecord
  belongs_to :job
  belongs_to :category
end

app/models/user_name.rb
class UserName < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # before_action :new_category, only: [:new]
  before_action :set_category, only: [:destroy, :show, :edit, :update]

  def index
    @categories = Category.all
  end

  def new
    new_category
  end

  def create
    new_category(category_params)
    if @category.save
      redirect_to category_path(@category)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @category.update(category_params)
      flash.notice = "Category #{@category.title} has been updated!"
      redirect_to category_path(@category)
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    flash.notice = "Category #{@category.title} has been deleted!"
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:title)
  end

  def set_category
    @category = Category.find(params[:id])
  end

  def new_category(params = nil)
    @category = Category.new(params)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_commentable
  before_action :set_job, :set_company, only: [:create]


  def new
    @comment = Comment.new
  end

  def create
    @comment = @commentable.comments.new comment_params

    if @comment.save
      redirect_to company_job_path(@company, @job), notice: 'Your comment was successfully posted!'
    else
      redirect_to :back, notice: "Your comment wasn't posted!"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def find_commentable
    @commentable = Comment.find_by_id(params[:id]) if params[:comment_id]
    @commentable = Job.find_by_id(params[:job_id]) if params[:job_id]
  end

  def set_job
    @job = Job.find(params[:job_id])
  end

  def set_company
    @company = @job.company
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      flash[:success] = "#{@company.name} added!"
      redirect_to company_path(@company)
    else
      render :new
    end
  end

  def show
    @company = Company.find(params[:id])
    # redirect_to company_jobs_path(company)
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    @company.update(company_params)
    if @company.save
      flash[:success] = "#{@company.name} updated!"
      redirect_to company_path(@company)
    else
      render :edit
    end
  end

  def destroy
    company = Company.find(params[:id])
    company.destroy

    flash[:success] = "#{company.name} was successfully deleted!"
    redirect_to companies_path
  end


  private

  def company_params
    params.require(:company).permit(:name, :city)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @company = Company.find(params[:company_id])
    @contact = @company.contacts.new(contact_params)
    if @contact.save
      redirect_to company_path(@company)
    else
      :back
    end
  end


  private

  def contact_params
    params.require(:contact).permit(:name, :position, :email)
  end
end

app/controllers/dasbhoards_controller.rb
class DashboardsController < ApplicationController

  def show
  end
  
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_company, except: [:update, :city_sort]
  before_action :set_job, except: [:index, :create, :new, :city_sort]

  def index
    @jobs = @company.jobs
  end

  def new
    @job = Job.new()
  end

  def create
    @job = @company.jobs.new(job_params)
    if @job.save
      flash[:success] = "You created #{@job.title} at #{@company.name}"
      redirect_to company_job_path(@company, @job)
    else
      render :new
    end
  end

  def show
    @job = Job.find(params[:id])
    @comments = @job.comments
    @comment = Comment.new
  end

  def edit
  end

  def update
    if @job.update(job_params)
      redirect_to company_jobs_path(@job)
    else
      render :edit
    end
  end

  def destroy
    @job.destroy
    redirect_to company_path(@company)
  end

  def city_sort
    byebug
    @jobs = city_find
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :level_of_interest, :city,
                                :category_id)
  end

  def set_company
    @company = Company.find(params[:company_id])
  end

  def set_job
    @job = Job.find(params[:id])
  end

  def self.sort_level_of_interest
    @jobs = Job.sort(:level_of_interest).reverse
  end

  def self.group_level_of_interest
    @grouped_jobs = Job.where
  end

  def city_find
    Job.where(city: params[:name])
  end

  def self.all_cities
    Job.distinct.pluck(:city)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <%= render partial: "shared/errors", locals: { target: @category } %>
  
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit %>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit <%= @category.title %></h1>

<%= render partial: "form" %>

app/views/categories/index.html.erb
<h1>Categories</h1>
<p><%= link_to "New Category", new_category_path %></p>

<ul>
  <% @categories.each do |category| %>
    <li>
      <h2><%= link_to category.title, category_path(category) %>
      <h6><%= link_to "Edit #{category.title}", edit_category_path(category) %>
          <%= link_to "Delete #{category.title}", category_path(category), method: :delete %></h6>
      </h2>
    </li>
  <% end %>
</ul>

app/views/categories/new.html.erb
<h1>New Category</h1>
<p><%= link_to "Home", root_path %></p>
<%= render partial: "form" %>

app/views/categories/show.html.erb
<h2><%= @category.title %></h2>
<p><%= link_to "Edit", edit_category_path(@category) %></p>
<p><%= link_to "Delete", category_path(@category), method: :delete %></p>
<p><%= link_to "Categories", categories_path %></p>
<p><%= link_to "Home", root_path %></p>


<ul>
  <% Job.where(category_id: @category.id).each do |job| %>
    <li><%= link_to job.title, company_job_path(job) %> - <%= link_to job.company.name, company_path(job.company) %></li>
  <% end %>
</ul>

app/views/comments/_comment.html.erb
<li>
  <%= comment.body %> -
  <small>Submitted <%= time_ago_in_words(comment.created_at) %> ago</small>

  <!-- <%= form_for [@job, Comment.new] do |f| %>
      <%= f.text_area :body, placeholder: "Add a Reply" %><br/>
      <%= f.submit "Reply"  %>
      <% end %> -->

  <ul>
    <%= render partial: 'comments/comment', collection: comment.comments  %>
  </ul>

</li>

app/views/companies/_form.html.erb
<%= form_for @company do |f| %>
  <%= render partial: "shared/errors", locals: { target: @company } %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/companies/edit.html.erb
<h2>Edit <%= @company.name %> here!</h2>

<%= render partial: "form" %>

app/views/companies/index.html.erb
<h3>All Companies</h3>

<ul>
  <% @companies.each do |company| %>
  <li class=company_<%= company.id %>>
    <%= link_to company.name, company_path(company) %>: 
    <%= link_to "Edit", edit_company_path(company) %>
    <%= link_to "Delete", company_path(company), method: "delete" %>
  </li>
  <% end %>
</ul>

app/views/companies/new.html.erb
<h2>Create a new company here!</h2>

<%= render partial: "form" %>

app/views/companies/show.html.erb
All Jobs for <strong><%= @company.name %></strong>

<% @company.jobs.each do |job| %>
  <ul><%= link_to job.title, company_job_path(@company, job) %></ul>
<% end %>
<h4>Contact : </h4>
<ul>
  <% @company.contacts.each do |contact| %>
    <li>Name: <%= contact.name %> Position: <%= contact.position %>  Email: <%= contact.email %></li>
  <% end %>
</ul>

<%= render partial: 'contacts/contact' %>

app/views/contacts/_contact.html.erb
<%= form_for [@company, Contact.new] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :position %>
  <%= f.text_field :position %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.submit "Create Contact"%>
<% end %>

app/views/dashboards/show.html.erb
<h1 class="">Dashboard</h1>

<h3>Top Three Jobs by Interest Level</h3>
<ul>
  <li>1st -- <%= Job.sort_level_of_interest.first %></li>
  <li>2nd -- <%= Job.sort_level_of_interest.second %></li>
  <li>3rd -- <%= Job.sort_level_of_interest.third %></li>
</ul>

<h3>Jobs By level of Interest</h3>
<ul>
  <li>Interest</li>
  <ul>0-20 -- <% Job.group_level_of_interest(0, 20).each do |job| %>
    <li><%= job.title %></li>
  <% end %>
  </ul>
  <ul>21-40 -- <% Job.group_level_of_interest(21,40).each do |job| %>
    <li><%= job.title %></li>
  <% end %>
  </ul>
  <ul>41-60 -- <% Job.group_level_of_interest(41, 60).each do |job| %>
    <li><%= job.title %></li>
  <% end %>
  </ul>
  <ul>61-80 -- <% Job.group_level_of_interest(61, 80).each do |job| %>
    <li><%= job.title %></li>
  <% end %>
  </ul>
  <ul>81-100 -- <%= Job.group_level_of_interest(81, 100).each do |job| %>
    <li><%= job.title %></li>
  <% end %>
  </ul>
</ul>

<h3>Jobs by City</h3>

<ul>
  <% Job.all_cities.each do |city| %>
    <ul><%= city %>
      <% Job.where(city: city).each do |job| %>
        <li><%= link_to job.title, company_job_path(job.company, job) %></li>
      <% end %>
    </ul>
  <% end %>
</ul>

app/views/jobs/_form.html.erb
<%= form_for [@company, @job] do |f| %>
  <%= render partial: "shared/errors", locals: { target: @job } %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :level_of_interest %>
  <%= f.number_field :level_of_interest %>

  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.label :category_id %>
  <%= f.select(:category_id, options_for_select(Category.all.map {|c| [c.title, c.id]}), { :include_blank => "Please select category"}, {:class => "form-control"}) %>

  <%= link_to "Create Category", new_category_path %><br />

  <%= f.submit %>
<% end %>

app/views/jobs/_job.html.erb
<% @jobs.each do |job| %>
  <ul><%= link_to job.title, company_job_path(@company, job) %> at <%= job.company.name %></ul>
<% end %>

app/views/jobs/city_sort.html.erb
All Jobs for <strong><%= @jobs.first.city %></strong>

<ul>
  <% @jobs.each do |job| %>
    <li><%= link_to job.title, company_job_path(job.company, job) %>--<%= link_to job.company.name, company_path(job.company)%></li>
  <% end %>
</ul>

app/views/jobs/comment.html.erb
<%= form_for @comment do |f| %>
  <%= f.label :context %>
  <%= f.text_field : %>
<% end %>

app/views/jobs/edit.html.erb
<h2>Edit job <%= @job.id %> for <%= @company.name %>!</h2>

<%= render partial: "form" %>

app/views/jobs/index.html.erb
All Jobs for <strong><%= @company.name %></strong>

<% @jobs.each do |job| %>
  <ul><%= job.title %> at <%= job.company.name %></ul>
<% end %>

app/views/jobs/new.html.erb
<h2>Create a new job at <%= @company.name %> here!</h2>

<%= render partial: "form" %>

app/views/jobs/show.html.erb
Title: <%= @job.title %>
<br>

Description: <%= @job.description %>
<br>

Level of Interest: <%= @job.level_of_interest %>
<br>

City: <%= @job.city %>
<br>

Company: <%= link_to @job.company.name, company_path(@job.company) %><br />

<%= link_to "Delete", company_job_path(@job), method: :delete %>
<%= link_to "Edit", edit_company_job_path(@job) %>

<h3>Comments</h3>
<ul>
  <%= render(partial: 'comments/comment', collection: @job.comments.reverse) %>
</ul>

<%= form_for [@job, Comment.new] do |f| %>
<%= f.text_area :body, placeholder: "Add a comment" %><br/>
<%= f.submit "Add Comment" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: name %>
  <% end %>
<%= yield %>

</body>
</html>

app/views/shared/_errors.html.erb
<% if target.errors.any? %>
  <h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% target.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>